#############################################################################
# Makefile for building: CODEA-Paradiseo
# Generated by qmake (2.01a) (Qt 4.6.0) on: Tue May 10 15:44:04 2011
# Project:  CODEA-Paradiseo.pro
# Template: app
# Command: /opt/streamline/bin/qmake -unix -o Makefile CODEA-Paradiseo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -W -O2 -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/streamline-packages/qt4-4.6.0/mkspecs/default -I. -I/opt/streamline-packages/qt4-4.6.0/include/QtCore -I/opt/streamline-packages/qt4-4.6.0/include -I../software/paradiseo-1.2.1/paradiseo-moeo/src -I../software/paradiseo-1.2.1/paradiseo-moeo/src/utils -I../software/paradiseo-1.2.1/paradiseo-eo/src -I../software/paradiseo-1.2.1/paradiseo-eo/src/utils -I../software/paradiseo-1.2.1/paradiseo-mo/src -I/work/work3/psxjpc/software/paradiseo-1.2.1/paradiseo-mo/src/utils -I/work/work3/psxjpc/software/boost_1_46_1 -Icore -I/opt/local/include/ -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/opt/streamline-packages/qt4-4.6.0/lib
LIBS          = $(SUBLIBS)  -L/opt/streamline-packages/qt4-4.6.0//lib /work/work3/psxedc/software/paradiseo-1.2.1/paradiseo-moeo/build/lib/libmoeo.a /work/work3/psxedc/software/paradiseo-1.2.1/paradiseo-eo/build/lib/libeo.a /work/work3/psxedc/software/paradiseo-1.2.1/paradiseo-eo/build/lib/libeoutils.a /work/work3/psxjpc/software/boost_1_46_1/stage/lib/libboost_thread.so -lQtCore -L/opt/streamline-packages/qt4-4.6.0//lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/streamline/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /opt/streamline-packages/qt4-4.6.0/mkspecs/common/g++.conf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/common/unix.conf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/common/linux.conf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/qconfig.pri \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt_functions.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt_config.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/exclusive_builds.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/default_pre.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/release.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/default_post.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/warn_off.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/unix/thread.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/moc.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/resources.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/uic.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/yacc.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/lex.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/include_source_dir.prf \
		CODEA-Paradiseo.pro
QMAKE_TARGET  = CODEA-Paradiseo
DESTDIR       = 
TARGET        = CODEA-Paradiseo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CODEA-Paradiseo.pro  /opt/streamline-packages/qt4-4.6.0/mkspecs/default/qmake.conf /opt/streamline-packages/qt4-4.6.0/mkspecs/common/g++.conf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/common/unix.conf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/common/linux.conf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/qconfig.pri \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt_functions.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt_config.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/exclusive_builds.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/default_pre.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/release.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/default_post.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/warn_off.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/unix/thread.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/moc.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/resources.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/uic.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/yacc.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/lex.prf \
		/opt/streamline-packages/qt4-4.6.0/mkspecs/features/include_source_dir.prf \
		/opt/streamline-packages/qt4-4.6.0/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile CODEA-Paradiseo.pro
/opt/streamline-packages/qt4-4.6.0/mkspecs/common/g++.conf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/common/unix.conf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/common/linux.conf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/qconfig.pri:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt_functions.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt_config.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/exclusive_builds.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/default_pre.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/release.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/default_post.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/warn_off.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/qt.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/unix/thread.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/moc.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/resources.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/uic.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/yacc.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/lex.prf:
/opt/streamline-packages/qt4-4.6.0/mkspecs/features/include_source_dir.prf:
/opt/streamline-packages/qt4-4.6.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile CODEA-Paradiseo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CODEA-Paradiseo1.0.0 || $(MKDIR) .tmp/CODEA-Paradiseo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CODEA-Paradiseo1.0.0/ && $(COPY_FILE) --parents core/CODEATypes.h core/neighborhood.h libs/concurrentQueue.h core/mailBox.h core/agent.h core/container.h problems/VRPTW/moeoVRPUtils.h problems/VRPTW/moeoVRPStat.h problems/VRPTW/moeoVRPQuadCrossover.h problems/VRPTW/moeoVRPObjectiveVectorTraits.h problems/VRPTW/moeoVRPMutation.h problems/VRPTW/moeoVRPInit.h problems/VRPTW/moeoVRPEvalFunc.h problems/VRPTW/moeoVRP.h dummyPhase.h VRPInstanceLoader.h neighborhoods/staticNeighborhood.h do_makes/make_neighborhood.h problems/VRPTW/do_makes.h core/eoSingleOp.h core/eoQuadSingleGenOp.h core/eoMonSingleGenOp.h agents/moeoJFOPhaseAlgorithm.h core/phase.h agents/defaultCommunicationPhase.h problems/VRPTW/moeoVRPIterSwap.h core/moMOLS.h core/moNeighborhoodExplorer.h libs/conversions.h core/moeoCoverageMetric.h .tmp/CODEA-Paradiseo1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/CODEA-Paradiseo1.0.0/ && (cd `dirname .tmp/CODEA-Paradiseo1.0.0` && $(TAR) CODEA-Paradiseo1.0.0.tar CODEA-Paradiseo1.0.0 && $(COMPRESS) CODEA-Paradiseo1.0.0.tar) && $(MOVE) `dirname .tmp/CODEA-Paradiseo1.0.0`/CODEA-Paradiseo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CODEA-Paradiseo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp problems/VRPTW/moeoVRPEvalFunc.h \
		problems/VRPTW/moeoVRPUtils.h \
		problems/VRPTW/moeoVRPObjectiveVectorTraits.h \
		problems/VRPTW/moeoVRP.h \
		core/agent.h \
		core/container.h \
		core/CODEATypes.h \
		core/mailBox.h \
		libs/concurrentQueue.h \
		core/neighborhood.h \
		core/phase.h \
		problems/VRPTW/moeoVRPQuadCrossover.h \
		problems/VRPTW/moeoVRPMutation.h \
		problems/VRPTW/moeoVRPInit.h \
		problems/VRPTW/moeoVRPIterSwap.h \
		problems/VRPTW/do_makes.h \
		core/eoSingleOp.h \
		core/eoQuadSingleGenOp.h \
		core/eoMonSingleGenOp.h \
		do_makes/make_neighborhood.h \
		neighborhoods/staticNeighborhood.h \
		core/moMOLS.h \
		agents/moeoJFOPhaseAlgorithm.h \
		agents/defaultCommunicationPhase.h \
		dummyPhase.h \
		libs/conversions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

